# Generated by Django 5.0.7 on 2024-08-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'permissions': [('free', 'Free Perm'), ('basic', 'Basic Perm'), ('advance', 'Advance Perm'), ('pro', 'Pro Perm')],
            },
        ),
    ]
