# Generated by Django 5.0.7 on 2024-08-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0004_alter_subscription_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['free', 'basic', 'advance', 'pro'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
